# author : Avinandan Sengupta 
# reg no : 2010CSY7543
# course : CSL630
#
# description : makefile for fibheap project

TYPE=exe
NAME=fibheap
SPECIAL_INCS=-I../../fibheap_lib/include
LIBPATH=../../fibheap_lib/work
LIBS=-lfibheap$(SUFFIX) -lm
DEPS=libfibheap$(SUFFIX).a

include ../../c_cpp_make.rules

# end of file

