# author : Avinandan Sengupta 
# reg no : 2010CSY7543
# course : CSL630
#
# description : makefile for fibheap project

TYPE=static_lib
NAME=libfibheap

include ../../c_cpp_make.rules

# end of file

